<script setup>
import { onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { archiveEpisode, createEpisode, listEpisodes, updateEpisode } from '@/api/shot-grid/episodes'
import { archiveScene, createScene, listScenes, updateScene } from '@/api/shot-grid/scenes'
import { getErrorDetails } from '@/utils/requestErrors'
import ProjectDetailLayout from './ProjectDetailLayout.vue'

const props = defineProps({ projectId: { type: String, required: true } })
const episodes = ref([]), scenes = ref([]), selected = ref(null), total = ref(0), pageNum = ref(1), loading = ref(false), error = ref(''), forbidden = ref(false), dialog = ref(false), editing = ref(null), kind = ref('episode')
const form = reactive({ number: 1, name: '', sortOrder: 0 }); let controller
async function loadEpisodes() { controller?.abort(); controller = new AbortController(); loading.value = true; error.value = ''; forbidden.value = false; try { const data = await listEpisodes(props.projectId, { pageNum: pageNum.value, pageSize: 20 }, { signal: controller.signal }); episodes.value = data?.rows || []; total.value = Number(data?.total || 0); if (!selected.value && episodes.value.length) await selectEpisode(episodes.value[0]) } catch (reason) { if (reason?.code !== 'ERR_CANCELED') { const info = getErrorDetails(reason); forbidden.value = info.status === 403; error.value = info.message } } finally { loading.value = false } }
async function selectEpisode(episode) { selected.value = episode; scenes.value = []; try { const data = await listScenes(props.projectId, episode.episodeId, { pageNum: 1, pageSize: 100 }); scenes.value = data?.rows || [] } catch (reason) { error.value = getErrorDetails(reason).message } }
function open(type, row) { kind.value = type; editing.value = row || null; Object.assign(form, { number: row?.episodeNo ?? row?.sceneNo ?? (type === 'episode' ? 1 : 0), name: row?.episodeName ?? row?.sceneName ?? '', sortOrder: row?.sortOrder ?? 0 }); dialog.value = true }
async function save() { try { const isEpisode = kind.value === 'episode'; const payload = isEpisode ? { episodeNo: form.number, episodeName: form.name, sortOrder: form.sortOrder } : { sceneNo: form.number, sceneName: form.name, sortOrder: form.sortOrder }; if (editing.value) { payload.lockVersion = editing.value.lockVersion; if (isEpisode) await updateEpisode(props.projectId, editing.value.episodeId, payload); else await updateScene(props.projectId, editing.value.sceneId, payload) } else if (isEpisode) await createEpisode(props.projectId, payload); else await createScene(props.projectId, selected.value.episodeId, payload); dialog.value = false; ElMessage.success('保存成功'); await loadEpisodes(); if (selected.value) await selectEpisode(selected.value) } catch (reason) { const info = getErrorDetails(reason); if (info.status === 409) ElMessageBox.alert(`${info.message}。请刷新后比较最新数据。`, '数据版本冲突', { type: 'warning' }); else error.value = info.message } }
async function archive(type, row) { try { await ElMessageBox.confirm('归档后默认列表将不再展示，确定继续？', '确认归档', { type: 'warning' }); if (type === 'episode') await archiveEpisode(props.projectId, row.episodeId, row.lockVersion); else await archiveScene(props.projectId, row.sceneId, row.lockVersion); await loadEpisodes() } catch (reason) { if (!['cancel', 'close'].includes(reason)) { const info = getErrorDetails(reason); if (info.status === 409) ElMessage.warning('数据已更新，请刷新并比较最新数据。'); else error.value = info.message } } }
onMounted(loadEpisodes); onBeforeUnmount(() => controller?.abort())
</script>
<template><ProjectDetailLayout :project-id="projectId"><section class="scene-workspace"><header><div><h2>集与场次</h2><p>左侧选择集，右侧分页维护其场次。</p></div><el-button type="primary" @click="open('episode')">创建集</el-button></header><div v-if="forbidden" class="state-panel state-panel--error">无权限查看项目结构。</div><div v-else-if="error" class="state-panel state-panel--error">{{ error }} <el-button @click="loadEpisodes">重试</el-button></div><div v-else v-loading="loading" class="master-detail"><aside><button v-for="episode in episodes" :key="episode.episodeId" :class="{ active: selected?.episodeId === episode.episodeId }" @click="selectEpisode(episode)"><b>EP{{ String(episode.episodeNo).padStart(3, '0') }}</b><span>{{ episode.episodeName || '未命名集' }}</span><i @click.stop="open('episode', episode)">编辑</i><i @click.stop="archive('episode', episode)">归档</i></button><p v-if="!episodes.length">暂无集</p><el-pagination small :current-page="pageNum" :page-size="20" :total="total" layout="prev, next" @current-change="(page) => { pageNum = page; loadEpisodes() }" /></aside><main><header><h3>{{ selected?.episodeName || '请选择集' }} · 场次</h3><el-button :disabled="!selected" @click="open('scene')">创建场次</el-button></header><el-table :data="scenes" empty-text="暂无场次"><el-table-column prop="sceneCode" label="场次"/><el-table-column prop="sceneName" label="名称"/><el-table-column prop="shotCount" label="镜头数"/><el-table-column label="操作"><template #default="{ row }"><el-button link @click="open('scene', row)">编辑</el-button><el-button link type="danger" @click="archive('scene', row)">归档</el-button></template></el-table-column></el-table></main></div></section><el-dialog v-model="dialog" :title="`${editing ? '编辑' : '创建'}${kind === 'episode' ? '集' : '场次'}`" width="440px"><el-form label-position="top"><el-form-item label="编号"><el-input-number v-model="form.number" :min="kind === 'episode' ? 1 : 0"/></el-form-item><el-form-item label="名称"><el-input v-model="form.name" maxlength="200"/></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sortOrder" :min="0"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></ProjectDetailLayout></template>
