<script setup>
import { onBeforeUnmount, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { listAssets } from '@/api/shot-grid/assets'
import { getErrorDetails } from '@/utils/requestErrors'
const props = defineProps({ projectId: { type: String, default: '' } }), route = useRoute(), router = useRouter()
const type = ref(''), keyword = ref(''), rows = ref([]), total = ref(0), pageNum = ref(1), loading = ref(false), error = ref(''), forbidden = ref(false); let controller, timer
const project = () => props.projectId || String(route.query.projectId || '')
async function load() { controller?.abort(); if (!project()) return; controller = new AbortController(); loading.value = true; error.value = ''; forbidden.value = false; try { const data = await listAssets(project(), { assetType: type.value, keyword: keyword.value, pageNum: pageNum.value, pageSize: 20 }, { signal: controller.signal }); rows.value = data?.rows || []; total.value = Number(data?.total || 0) } catch (reason) { if (reason?.code !== 'ERR_CANCELED') { const info = getErrorDetails(reason); forbidden.value = info.status === 403; error.value = info.message } } finally { loading.value = false } }
watch([() => props.projectId, type], () => { pageNum.value = 1; load() }, { immediate: true }); watch(keyword, () => { clearTimeout(timer); timer = setTimeout(() => { pageNum.value = 1; load() }, 300) }); onBeforeUnmount(() => { controller?.abort(); clearTimeout(timer) })
</script>
<template><section class="page domain-page"><span class="eyebrow">ASSETS</span><h1>资产库</h1><div class="asset-filters"><el-input v-model="keyword" clearable placeholder="搜索资产名称"/><el-radio-group v-model="type"><el-radio-button value="">全部</el-radio-button><el-radio-button value="Character">Character</el-radio-button><el-radio-button value="Environment">Environment</el-radio-button><el-radio-button value="Prop">Prop</el-radio-button></el-radio-group></div><div v-if="!project()" class="state-panel">请先选择项目。</div><div v-else-if="forbidden" class="state-panel state-panel--error">无权限查看当前项目资产。</div><div v-else-if="error" class="state-panel state-panel--error">{{ error }} <el-button @click="load">重试</el-button></div><div v-else v-loading="loading"><div class="asset-grid"><article v-for="asset in rows" :key="asset.assetId" tabindex="0" @click="router.push({ name: 'AssetDetail', params: { assetId: asset.assetId }, query: { projectId: project() } })"><el-tag>{{ asset.assetType }}</el-tag><h2>{{ asset.assetName }}</h2><p>{{ asset.description || '暂无描述' }}</p><small>{{ asset.itemCount || 0 }} 个制作分项 · {{ asset.aggregateStatusLabel || '未开始' }}</small></article></div><div v-if="!rows.length && !loading" class="state-panel">当前条件下暂无资产。</div><el-pagination :current-page="pageNum" :page-size="20" :total="total" layout="total, prev, pager, next" @current-change="(page) => { pageNum = page; load() }"/></div></section></template>
