<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute } from 'vue-router'
import { getShot } from '@/api/shot-grid/shots'
import { bindRequirement, closeRequirement, listRequirementCandidates, listRequirements } from '@/api/shot-grid/requirements'
import { getErrorDetails } from '@/utils/requestErrors'
const props = defineProps({ projectId: { type: String, required: true } })
const route = useRoute(), rows = ref([]), total = ref(0), loading = ref(false), error = ref('')
const query = reactive({ pageNum: 1, pageSize: 20, status: '', assetType: '', shotId: route.query.shotId || '' })
const candidates = reactive({ visible: false, loading: false, rows: [], requirement: null, selectedId: null, keyword: '' })
async function load() { loading.value = true; error.value = ''; try { const data = await listRequirements(props.projectId, query); rows.value = data.rows; total.value = data.total } catch (e) { error.value = getErrorDetails(e).message } finally { loading.value = false } }
async function loadCandidates() { candidates.loading = true; try { const data = await listRequirementCandidates(props.projectId, candidates.requirement.requirementId, { keyword: candidates.keyword }); candidates.rows = data.rows } catch (e) { ElMessage.error(getErrorDetails(e).message) } finally { candidates.loading = false } }
async function openCandidates(row) { candidates.visible = true; candidates.requirement = row; candidates.selectedId = null; candidates.keyword = ''; await loadCandidates() }
async function bind() { if (!candidates.selectedId) return ElMessage.warning('请选择候选资产'); try { const result = await bindRequirement(props.projectId, candidates.requirement.requirementId, candidates.selectedId, candidates.requirement.lockVersion); await Promise.all([getShot(props.projectId, result.shotId), load()]); candidates.visible = false; ElMessage.success('绑定成功，镜头资产关系与待处理数量已刷新') } catch (e) { ElMessage.error(getErrorDetails(e).message) } }
async function ignore(row) { try { const { value } = await ElMessageBox.prompt('请输入忽略/关闭原因', '关闭需求', { inputValidator: (v) => Boolean(v?.trim()) || '原因不能为空' }); await closeRequirement(props.projectId, row.requirementId, row.lockVersion, value.trim()); await load(); ElMessage.success('需求已关闭') } catch (e) { if (e !== 'cancel' && e !== 'close') ElMessage.error(getErrorDetails(e).message) } }
onMounted(load)
</script>
<template><section class="page domain-page"><header class="page-heading"><div><span class="eyebrow">ASSET REQUIREMENTS</span><h1>待匹配需求</h1><p class="lead">只人工选择明确类型的项目内有效资产；不会从描述或备注猜测 Character/Prop。</p></div></header>
<div class="filter-bar"><el-select v-model="query.status" clearable placeholder="状态" @change="load"><el-option label="待匹配" value="pending"/><el-option label="冲突" value="conflict"/></el-select><el-select v-model="query.assetType" clearable placeholder="类型" @change="load"><el-option v-for="type in ['Character','Environment','Prop']" :key="type" :label="type" :value="type"/></el-select><el-input v-model="query.shotId" clearable placeholder="镜头 ID" @keyup.enter="load"/><el-button @click="load">查询</el-button></div>
<el-alert v-if="error" type="error" :closable="false" :title="error"/><el-table v-loading="loading" :data="rows" border><el-table-column prop="sourceSheet" label="来源 Sheet"/><el-table-column prop="sourceRowNumber" label="行号" width="80"/><el-table-column prop="shotNo" label="镜头" width="80"/><el-table-column prop="requirementName" label="需求名称"/><el-table-column prop="assetType" label="类型"/><el-table-column prop="resolutionStatus" label="状态"/><el-table-column prop="conflictReason" label="冲突原因"><template #default="{row}">{{ row.conflictReason || '—' }}</template></el-table-column><el-table-column label="操作" width="180"><template #default="{row}"><el-button link type="primary" @click="openCandidates(row)">选择候选</el-button><el-button link type="danger" @click="ignore(row)">忽略/关闭</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.pageNum" :page-size="query.pageSize" :total="total" @current-change="load"/>
<el-dialog v-model="candidates.visible" title="选择同项目、同类型的有效资产" width="680"><el-input v-model="candidates.keyword" clearable placeholder="按资产名称筛选" @keyup.enter="loadCandidates"><template #append><el-button @click="loadCandidates">搜索</el-button></template></el-input><el-table v-loading="candidates.loading" :data="candidates.rows" highlight-current-row @current-change="row => candidates.selectedId = row?.assetId"><el-table-column width="48"><template #default="{row}"><el-radio v-model="candidates.selectedId" :value="row.assetId"/></template></el-table-column><el-table-column prop="assetName" label="候选资产"/><el-table-column prop="assetType" label="类型"/></el-table><el-empty v-if="!candidates.loading && !candidates.rows.length" description="无候选资产"/><template #footer><el-button @click="candidates.visible=false">取消</el-button><el-button type="primary" :disabled="!candidates.selectedId" @click="bind">确认绑定</el-button></template></el-dialog></section></template>
